name: QuickSwitch
version: 1.0
author: NemoXFish
main: com.NemoXFish.quickswitch.QuickSwitch
api-verison: 1.16.4
commands:
  gmc:
    description: Switches player to creative
    usage: /<command>
  gms:
    description: Switches player to survival
    usage: /<command>
  gma:
    description: Switches player to adventure
    usage: /<command>
  gmsp:
    description: Switches player to spectator
    usage: /<command>